import type { Metadata } from 'next';
import { Lora } from 'next/font/google';
import { ThemeProvider } from './_components/theme-provider';

import './globals.css';
import { Nav } from './_components/nav';
import { Footer } from './_components/footer';

const lora = Lora({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={lora.className}>
        <ThemeProvider>
          <nav>
            <Nav />
          </nav>
          <main>{children}</main>
          <footer>
            <Footer />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
